export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOAD_USER = "LOAD_USER";
export const AUTH_FAILED = "AUTH_FAILED";
export const SET_LOADING = "SET_LOADING";

export const GET_PURCHASE = "GET_PURCHASE";
export const GET_PURCHASE_FAILED = "GET_PURCHASE_FAILED";
export const GET_PURCHASE_USING_PRODUCTNAME = "GET_PURCHASE_USING_PRODUCTNAME";
export const GET_PURCHASE_USING_PRODUCTNAME_FAILED =
  "GET_PURCHASE_USING_PRODUCTNAME_FAILED";
export const ADD_PURCHASE_RETURN = "ADD_PURCHASE_RETURN";
export const ADD_PURCHASE_RETURN_FAILED = "ADD_PURCHASE_RETURN_FAILED";
export const SAVE_NEW_PURCHASE = "SAVE_NEW_PURCHASE";
export const SAVE_NEW_PURCHASE_FAILED = "SAVE_NEW_PURCHASE_FAILED";
export const SAVE_EXISTING_PURCHASE = "SAVE_EXISTING_PURCHASE";
export const SAVE_EXISTING_PURCHASE_FAILED = "SAVE_EXISTING_PURCHASE_FAILED";

export const ADD_SALES = "ADD_SALES";
export const ADD_SALES_FAILED = "ADD_SALES_FAILED";
export const CLEAR_SALES_ERRORS = "CLEAR_SALES_ERRORS";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const ADD_NEW_PRODUCT_FAILED = "ADD_NEW_PRODUCT_FAILED";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_PRODUCT_FAILED = "EDIT_PRODUCT_FAILED";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const GET_CREDITORS = "GET_CREDITORS";
export const GET_CREDITORS_FAILED = "GET_CREDITORS_FAILED";
export const GET_CREDITOR = "GET_CREDITOR";
export const GET_CREDITOR_FAILED = "GET_CREDITOR_FAILED";
export const DELETE_CREDITOR = "DELETE_CREDITOR";
export const DELETE_CREDITOR_FAILED = "DELETE_CREDITOR_FAILED";
export const ADD_CREDITOR = "ADD_CREDITOR";
export const ADD_CREDITOR_FAILED = "ADD_CREDITOR_FAILED";
export const EDIT_CREDITOR = "EDIT_CREDITOR";
export const EDIT_CREDITOR_FAILED = "EDIT_CREDITOR_FAILED";

export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_CUSTOMERS_FAILED = "GET_CUSTOMERS_FAILED";
export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMER_FAILED = "GET_CUSTOMER_FAILED";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_FAILED = "DELETE_CUSTOMER_FAILED";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const ADD_CUSTOMER_FAILED = "ADD_CUSTOMER_FAILED";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const EDIT_CUSTOMER_FAILED = "EDIT_CUSTOMER_FAILED";

export const FILTER_CARDS = "FILTER_CARDS";
export const CLEAR_FILTER_CARDS = "CLEAR_FILTER_CARDS";
export const FILTER_EDIT_PRODUCT = "FILTER_EDIT_PRODUCT";
export const CLEAR_FILTER_EDIT_PRODUCT = "CLEAR_FILTER_EDIT_PRODUCT";
export const FILTER_DELETE_PRODUCT = "FILTER_DELETE_PRODUCT";
export const CLEAR_FILTER_DELETE_PRODUCT = "CLEAR_FILTER_DELETE_PRODUCT";
export const FILTER_PURCHASE_RETURN = "FILTER_PURCHASE_RETURN";
export const CLEAR_FILTER_PURCHASE_RETURN = "CLEAR_FILTER_PURCHASE_RETURN";
export const FILTER_PURCHASE_EXISTING_PRODUCT =
  "FILTER_PURCHASE_EXISTING_PRODUCT";
export const CLEAR_FILTER_PURCHASE_EXISTING_PRODUCT =
  "CLEAR_FILTER_PURCHASE_EXISTING_PRODUCT";

export const FILTER_SALES_RETURN = "FILTER_PURCHASE_RETURN";
export const CLEAR_FILTER_SALES_RETURN = "CLEAR_FILTER_PURCHASE_RETURN";
export const FILTER_ADD_SALES = "FILTER_ADD_SALES";
export const CLEAR_FILTER_ADD_SALES = "CLEAR_FILTER_ADD_SALES";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
